version: '3.0'
services:
 pycharm:
  build: .
  container_name: pycharm
  volumes:
   - /tmp/.X11-unix:/tmp/.X11-unix
   - /home/$USER/containers/pycharm/:/home/root/
  environment:
   - DISPLAY=unix$DISPLAY
   - VERSION=2017.2.1
