version: '3.0'
services:
 wireshark:
  build: .
  container_name: wireshark
  volumes:
   - /etc/localtime:/etc/localtime
   - /tmp/.X11-unix:/tmp/.X11-unix
   - /home/$USER/containers/wireshark:/home/wireshark
  environment:
   - DISPLAY=unix$DISPLAY
