version: '3.0'
services:
 gimp:
  build: .
  container_name: gimp
  volumes:
   - /etc/localtime:/etc/localtime
   - /tmp/.X11-unix:/tmp/.X11-unix
   - /home/$USER/Pictures:/home/gimp/Pictures
  environment:
   - DISPLAY=unix$DISPLAY
