version: '3.0'
services:
 libreoffice:
  build: .
  container_name: libreoffice
  volumes:
   - /etc/localtime:/etc/localtime
   - /tmp/.X11-unix:/tmp/.X11-unix
   - /home/$USER/containers/libreOffice:/home/libreoffice
  env_file:
   - env_file.env

